SportsStore/Components/NavigationMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;

        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products
                .Select(x=>new NavigationMenuResponceModel{DisplayCategory = x.CategoryDesciption, Category=x.Category})
                .Distinct()
                .OrderBy(x=>x.DisplayCategory));
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card-body m-1 p-1">
    <div class="bg-light p-1">
        <div>
            <h4>
                @Model.Name
                <span class="badge badge-pill badge-primary" style="float:right">
                    <small>@Model.Price.ToString("c")</small>
                </Span>
            </h4>
        </div>
        <div class="card-text p-1">@Model.Description</div>
    </div>
    <form id="@Model.ProductId"
          asp-action="AddToCart"
          asp-controller="Cart"
          method="post">
        <input type="hidden" asp-for="ProductId"/>
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
        <span class="card-text p-1">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float: right">Add To Cart</button>
        </span>
    </form>
</div>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" 
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
          asp-fallback-href="~/bootstrap/css/bootstrap.min.css" 
          asp-fallback-test-class="sr-only" 
          asp-fallback-test-property="position" 
          asp-fallback-test-value="absolute"/>

    <title>SportStore</title>
</head>
<bode>
    <div class="navbar navbar-dark bg-info" role="navigation">
        <a class="navbar-brand" href="#">Sports store</a>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</bode>
</html>